export const users = [
  {
    id: 1,
    name: "Nijin Nazar",
    about: "I am a MERN Stack developer and basically a Btech student.",
    domain: "Web Developer",
    image: "https://i.imgur.com/Sgze2oK.jpg",
    skills: [
      "ReactJS",
      "Nodejs",
      "CSS",
      "Electron",
      "SparkAI",
      "MERN",
      "Javascript",
    ],
    available: true,
    online: true,
    lastseeen: "1",
    createdAt: "August 25,2020",
    location: "Kerala,India",
  },
  {
    id: 2,
    name: "Andrew Alex",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Imperdiet massa tincidunt nunc pulvinar sapien. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Arcu cursus vitae congue mauris rhoncus aenean vel. Suspendisse faucibus interdum posuere lorem.",
    domain: "Web Developer",
    image:
      "https://i.ibb.co/61FsjZz/albert-dera-ILip77-Sbm-OE-unsplash-min.jpg",
    skills: [
      "Algorithms",
      "Analytical Skills",
      "Big Data",
      "Calculating",
      "Compiling Statistics",
      "Data Analytics",
      "Data Mining",
      "Database Design",
      "Database Management",
      "Documentation",
    ],
    available: false,
    online: false,
    lastseeen: "4",
    createdAt: "October 2,2020",
    location: "Philadelphia,California",
  },
  {
    id: 3,
    name: "Jessica",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Imperdiet massa tincidunt nunc pulvinar sapien. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Arcu cursus vitae congue mauris rhoncus aenean vel. Suspendisse faucibus interdum posuere lorem.",
    domain: "Web Developer",
    image: "https://i.imgur.com/3rUsasC.jpg",
    skills: [
      "Modeling",
      "Modification",
      "Needs Analysis",
      "Quantitative Research",
      "Quantitative Reports",
      "Statistical Analysis",
      "Applications",
      "Certifications",
      "Coding",
      "Computing",
      "Configuration",
      "Customer Support",
      "Debugging",
    ],
    available: true,
    online: true,
    lastseeen: "1",
    createdAt: "February 22, 2018",
    location: "Kerala,India",
  },
  {
    id: 4,
    name: "John Jacob",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Imperdiet massa tincidunt nunc pulvinar sapien. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Arcu cursus vitae congue mauris rhoncus aenean vel. Suspendisse faucibus interdum posuere lorem.",
    domain: "Web Developer",
    image: "https://i.imgur.com/ZDRC7wE.jpg",
    skills: [
      "Design",
      "Development",
      "Hardware",
      "Implementation",
      "Information Technology",
      "Infrastructure",
      "Languages",
      "Maintenance",
      "Network Architecture",
      "Network Security",
      "Networking",
      "New Technologies",
    ],
    available: true,
    lastseeen: "2",
    createdAt: "February 29, 2017",
    location: "UK",
  },
  {
    id: 5,
    name: "Ellai",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Imperdiet massa tincidunt nunc pulvinar sapien. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Arcu cursus vitae congue mauris rhoncus aenean vel. Suspendisse faucibus interdum posuere lorem.",
    domain: "Web Developer",
    image: "https://i.imgur.com/6qiMNLI.jpg",
    skills: [
      "Operating Systems",
      "Programming",
      "Restoration",
      "Security",
      "Servers",
      "Software",
      "Solution Delivery",
      "Storage",
      "Structures",
      "Systems Analysis",
      "Technical Support",
      "Technology",
      "Testing",
      "Tools",
    ],
    available: true,
    lastseeen: "5",
    createdAt: "December 25, 2015",
    location: "Dubai, UAE",
  },
  {
    id: 6,
    name: "John Jacob",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Imperdiet massa tincidunt nunc pulvinar sapien. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Arcu cursus vitae congue mauris rhoncus aenean vel. Suspendisse faucibus interdum posuere lorem.",
    domain: "Web Developer",
    image: "https://i.imgur.com/6fJVYA6.jpg",
    skills: [
      "Training",
      "Troubleshooting",
      "Usability",
      "Benchmarking",
      "Budget Planning",
      "Engineering",
      "Fabrication",
      "Following Specifications",
      "Operations",
      "Performance Review",
      "Project Planning",
      "Quality Assurance",
      "Quality Control",
      "Scheduling",
    ],
    available: false,
    online: false,
    lastseeen: "3",
    createdAt: "December 25, 2015",
    location: "Maharashtra,India",
  },
  ,
  {
    id: 7,
    name: "John Jacob",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Imperdiet massa tincidunt nunc pulvinar sapien. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Arcu cursus vitae congue mauris rhoncus aenean vel. Suspendisse faucibus interdum posuere lorem.",
    domain: "Web Developer",
    image: "https://i.imgur.com/opHTtCC.jpg",
    skills: [
      "Task Delegation",
      "Blogging",
      "Digital Media",
      "Facebook",
      "Instagram",
      "Networking",
      "Pinterest",
      "SEO",
      "Social Media Platforms",
      "Twitter",
      "Web Analytics",
      "Client Relations",
      "Email",
      "Requirements Gathering",
      "Research",
      "Subject Matter Experts (SMEs)",
      "Technical Documentation",
    ],
    available: true,
    online: true,
    lastseeen: "3",
    createdAt: "December 25, 2015",
    location: "Telegana,India",
  },
];
